### ISSUE TITLE
Loop routing issue  

### ISSUE THREAD

**Issue by nrbray** [Cottand/selfhosted#4]
Dear Nico, 

I stumbled on this via [Lemmy](https://lemmy.ml/search?q=nixos%20networking) and wanted to pick your brains on the wireguard mesh setup you have.  Something that might be of interest to you is this description of the [the general recursive routing problem](https://utcc.utoronto.ca/~cks/space/blog/tech/IPRecursiveRoutingProblem) mentioned here:

https://utcc.utoronto.ca/~cks/space/blog/linux/LinuxIpFwmarkMasks  

I see you have noted [WireGuard#Loop_routing](https://wiki.archlinux.org/index.php/WireGuard#Loop_routing) the more common source from archlinux here:

https://github.com/Cottand/selfhosted/blame/7178c328f51ab4846b5d7268059fbfe4072c54ff/machines/bianco/wireguard.nix  

btw. I like your comment in relation to something for my [hobby](https://to1.uk/i) "If I was to found a startup tomorrow and had to develop its platform, I would reuse much of the technology I used for this side-project." 

Best regards Nigel

**Comment by Cottand** [comment]
Hi Nigel! Thanks for your message.

I noted Arch's docs but did not apply their suggested fix because this only happens with full-tunnel VPNs. I use [split-tunnelling](https://danstechjourney.com/wireguard-split-vs-full-tunnel/) for almost all my traffic (mostly because I don't want all traffic routed through any single node to avoid a SPOF).

Note the nodes themselves only speak to each other on `10.10.0.0/16`, so the endpoint is not routed via Wireguard's interface.

As for VPN catch-all traffic from my personal devices for `0.0.0.0/0`, it would suffer from this, but I have not seen it happen in practice.

**Comment by nrbray** [comment]
Thank you for the explanation.  The Arch work around is a horrible hack, but I have used it.  With my limited understanding I think the FWMark solves it, but am wondering if the [Namespace](https://www.wireguard.com/netns/) approach can be used and be more elegant?

**Comment by Cottand** [comment]
I don't know! I suggest you try and see :)

If you are trying to build a mesh network like mine, my suggestion is you set `AllowedIPs` to a subnet (like 10.0.0.0/24) and make your services speak to IPs in that subnet.

You will not have the recursive routing problem at all, because your traffic is not sent to the same IP that Wireguard is handshaking to.

P.S. Given this project does not have this problem (because it uses the above strategy) I will close this issue
